version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visionpro_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - vision-pro  

  app:
    build: .
    ports:
      - "81:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: visionpro_db
    networks:
      - vision-pro  
    depends_on:
       - db

volumes:
  mysql-data:
    driver: local

networks:
  vision-pro:
    driver: bridge
